var inp=document.getElementById('name');
var hd=document.getElementById('newchk');
var fm=document.getElementById('frm');
var sname=document.getElementById('stdname')
var div_res=document.getElementById('result_div');
var tq=document.getElementById('tquest')
var cqu=document.getElementById('cquest')
var WANS=document.getElementById('wans')
var PERC=document.getElementById('per')


var arr=[
    {
        'Q ' :'In MATLAB, the space located for the matrix generated from the spones command is _______':,
        'opt ' : ['Same as a sparse matrix','Same as the original matrix','Same as an identity matrix','Double that of the sparse matrix'],
        'cans' : '1'
        
    },
    {
        'Q ' :'To convert inches to millimeters, which of the following function is used?:',
        'opt ' : ['i2m = inline(d./25.4,d);','i2m = inline('d./25.4','d');','i2m = inline(d.*25.4)','function i2m = inline('d','d.*25.4');'],
        'cans' : '2'

    },
    {
        'Q ' :'Which one of the following is a legitimate variable names in MATLAB?:',
        'opt ' : ['4var','tax-rate','exam1.1','_input','sin'],
        'cans' : '5'

    },
    {
        'Q ' :'Which of the following MATLAB calculations would result the value 1?:',
        'opt ' : ['1+4/5','6/2*3','3^2/3*3','None of above'],
        'cans' : '4'

    },
    {
        'Q ' :'The default number of non-zero elements which can be put into the memory allocated by the spalloc command is > 1.:',
        'opt ' : ['True ','False'],
        'cans' : '2'

    },
    {
        'Q ' :'The pattern generated by the spy command is a measure of the number of zeros in the input matrix.:',
        'opt ' : ['True ','False'],
        'cans' : '2'

    },
    {
        'Q ' :'How much does the precision change while finding sin(x) using evalc and eval?:',
        'opt ' : ['10%','20%','2%','<No change'],
        'cans' : '1'

    },
    {
        'Q ' :'The input to the evalc command is given using {}.:',
        'opt ' : ['True ','False'],
        'cans' : '2'

    },
    {
        'Q ' :'The input to the eval command is given using [].:',
        'opt ' : ['True ','False'],
        'cans' : '2'

    },
    {
        'Q ' :'Which of the following is not a pre-defined variable in Matlab?:',
        'opt ' : ['pi','i','inf','gravity'],
        'cans' : '4'

    },
]

main_c=document.getElementById('main_div')
quest=document.getElementById('question')
var qno=document.getElementById('qof')
var p1=document.getElementById('option1')
var p2=document.getElementById('option2')
var p3=document.getElementById('option3')
var p4=document.getElementById('option4')
var result=document.getElementById('res')
var heading=document.getElementById('head')
var dp=document.getElementById('dp')
var agnbtn=document.getElementById('again')
var cquestion = 0
var score=0
var tQ=arr.length




function questionget(num){
    var q=arr[num]
    quest.textContent=(num+1) +' ).' + arr[num]['Q ']
    p1.textContent=q['opt '][0]
    p2.textContent=q['opt '][1]
    p3.textContent=q['opt '][2]
    p4.textContent=q['opt '][3]
    qno.textContent="Question "+(num+1) +" of 10"

}
function nextques(){
    var sOption = document.querySelector('input[type=radio]:checked');
  if (sOption == null) {
      alert('Please select your answer!');
      return;
  }
  var answer = sOption.value;
  console.log(arr[cquestion].cans)
  console.log(answer)
  if (arr[cquestion].cans  == answer) {
      score += 1;
  }
 console.log('score :', score)

sOption.checked = false;
cquestion++;
if (cquestion == tQ) {
    
    
    console.log("total question ",tQ)
    console.log('Name :',inp.value)
    console.log('score :', score)

   
   main_c.style.display='none'
   div_res.style.display=''
   result.style.display=''
   result.textContent='Your Total Score : '+score+'/ 10'
   agnbtn.style.display='block'
   sname.style.display=''
   tq.style.display=''
   tq.textContent="Total Question : "+  tQ
    sname.textContent="Student name : "+ inp.value
   dp.style.display='block'
   cqu.style.display=''
   cqu.textContent='Correct Answer : '+score
   WANS.style.display=''
   WANS.textContent='Wrong Answer : '+(10-score)
   heading.style.display=''
   heading.textContent='MATLAB QUIZ'
   PERC.style.display=''
   PERC.textContent='Percentage : '+((score*100)/10) +"%"


   

    if(score>=8){

    
    dp.innerHTML="<b>'Result : Excellent Good Job  Congratulation You Passed'</b>"

        }
    else if(score<=7 && score>=5){
        dp.innerHTML="<b>'Result : Congratulation You Passed'</b>"
    }
    else{
    dp.innerHTML="<b>'Result : fail'</b>"
}



   
   return
}





questionget(cquestion)

}
questionget(cquestion)

function restart(){
    location = 'index.html';

}



function getdata(){
    console.log(inp.value)
    if(inp.value==''){
        alert("Please Enter Your Name ")
    }
    else{
        console.log(fm)
        fm.style.display='none'
        main_c.style.display=''
        questionget(cquestion)

    }
}